apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-node
  labels:
    app: demo-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-node
  template:
    metadata:
      labels:
        app: demo-node
    spec:
      containers:
        - name: demo-node
          image: <ECR_REPO_URI>:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: 5432
            
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                name: postgres-secret
                key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                name: postgres-secret
                key: POSTGRES_DB 