apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-node-ingress
  annotation:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: demoeks.example.com
      http:
        paths:
        - path: /
          pathType: prefix
          backend:
            service:
              name: demo-node-svc
              port:
                number: 80