apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: demo-node-monitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: demo-node
  endpoints:
  - port: http-web   # same as service port name
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
      - default
